apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
  labels:
    purpose: secret
    env: dev
type: Opaque
data:
  username: "YWRtaW4="
  password: "YWRtaW4zMjE="

  # echo -n YWRtaW4= | base64 --decode
  # echo -n admin | base64